"""initial schema

Revision ID: a45e6da406df
Revises: 
Create Date: 2026-06-06 18:19:43.149941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a45e6da406df'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogue',
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('brand', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('scale', sa.String(length=16), nullable=True),
    sa.Column('year', sa.String(length=8), nullable=True),
    sa.Column('tone', sa.String(length=16), nullable=False),
    sa.Column('est_retail_price', sa.Integer(), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('submitted_by', sa.UUID(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('sku')
    )
    op.create_index('idx_catalogue_brand', 'catalogue', ['brand'], unique=False)
    op.create_index('idx_catalogue_category', 'catalogue', ['category'], unique=False)
    op.create_table('follows',
    sa.Column('follower_id', sa.UUID(), nullable=False),
    sa.Column('following_type', sa.String(length=16), nullable=False),
    sa.Column('following_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('follower_id', 'following_type', 'following_id')
    )
    op.create_index('idx_follows_follower', 'follows', ['follower_id'], unique=False)
    op.create_index('idx_follows_target', 'follows', ['following_type', 'following_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('handle', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('interests', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('deals_count', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('response_time_min', sa.Integer(), nullable=True),
    sa.Column('active_listings_count', sa.Integer(), nullable=False),
    sa.Column('portfolio_value', sa.Integer(), nullable=False),
    sa.Column('verified_items_count', sa.Integer(), nullable=False),
    sa.Column('followers_count', sa.Integer(), nullable=False),
    sa.Column('following_count', sa.Integer(), nullable=False),
    sa.Column('privacy_portfolio', sa.String(length=16), nullable=False),
    sa.Column('privacy_value', sa.String(length=16), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_seed_account', sa.Boolean(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('handle')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_handle', 'users', ['handle'], unique=False)
    op.create_table('communities',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_desc', sa.Text(), nullable=True),
    sa.Column('tag', sa.String(length=4), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('tone', sa.String(length=16), nullable=False),
    sa.Column('founder_id', sa.UUID(), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('post_count', sa.Integer(), nullable=False),
    sa.Column('post_mode', sa.String(length=16), nullable=False),
    sa.Column('rules', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('is_invite_only', sa.Boolean(), nullable=False),
    sa.Column('is_admin_created', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['founder_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('custom_title', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('verify_tier', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('is_listed', sa.Boolean(), nullable=False),
    sa.Column('photo_count', sa.Integer(), nullable=False),
    sa.Column('preorder_ordered_at', sa.Date(), nullable=True),
    sa.Column('preorder_eta', sa.Text(), nullable=True),
    sa.Column('wishlist_alert_enabled', sa.Boolean(), nullable=False),
    sa.Column('privacy', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('sku IS NOT NULL OR custom_title IS NOT NULL', name='items_has_identity'),
    sa.ForeignKeyConstraint(['sku'], ['catalogue.sku'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_items_sku', 'items', ['sku'], unique=False)
    op.create_index('idx_items_status', 'items', ['status'], unique=False)
    op.create_index('idx_items_user', 'items', ['user_id'], unique=False)
    op.create_index('idx_items_verify', 'items', ['verify_tier'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('ref_type', sa.String(length=24), nullable=True),
    sa.Column('ref_id', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifs_user', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.String(length=16), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reports_status', 'reports', ['status', 'created_at'], unique=False)
    op.create_index('idx_reports_target', 'reports', ['target_type', 'target_id'], unique=False)
    op.create_table('user_blocks',
    sa.Column('blocker_id', sa.UUID(), nullable=False),
    sa.Column('blocked_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blocker_id', 'blocked_id')
    )
    op.create_table('community_join_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('community_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('community_members',
    sa.Column('community_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('community_id', 'user_id')
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('community_id', sa.String(length=32), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('venue', sa.Text(), nullable=True),
    sa.Column('online_url', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interested_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('is_admin_created', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_category', 'events', ['category'], unique=False)
    op.create_index('idx_events_community', 'events', ['community_id'], unique=False)
    op.create_table('item_photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('phash', sa.Text(), nullable=True),
    sa.Column('is_verify_photo', sa.Boolean(), nullable=False),
    sa.Column('is_challenge_shot', sa.Boolean(), nullable=False),
    sa.Column('watermarked', sa.Boolean(), nullable=False),
    sa.Column('is_duplicate_flag', sa.Boolean(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_photos_item', 'item_photos', ['item_id'], unique=False)
    op.create_table('listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('retail_price', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=24), nullable=False),
    sa.Column('condition_notes', sa.Text(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('trade_willing', sa.Boolean(), nullable=False),
    sa.Column('ships_from_city', sa.Text(), nullable=True),
    sa.Column('ships_nationwide', sa.Boolean(), nullable=False),
    sa.Column('shipping_cost', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('terms', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('saves_count', sa.Integer(), nullable=False),
    sa.Column('watching_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_listings_created', 'listings', ['created_at'], unique=False)
    op.create_index('idx_listings_seller', 'listings', ['seller_id'], unique=False)
    op.create_index('idx_listings_sku', 'listings', ['sku'], unique=False)
    op.create_index('idx_listings_status', 'listings', ['status'], unique=False)
    op.create_table('saved_searches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=True),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('custom_query', sa.Text(), nullable=True),
    sa.Column('max_price', sa.Integer(), nullable=True),
    sa.Column('min_condition', sa.String(length=24), nullable=True),
    sa.Column('alert_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_searches_sku', 'saved_searches', ['sku'], unique=False)
    op.create_index('idx_searches_user', 'saved_searches', ['user_id'], unique=False)
    op.create_table('deals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=True),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('agreed_price', sa.Integer(), nullable=True),
    sa.Column('deal_type', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('initiated_by', sa.String(length=8), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seller_rating', sa.SmallInteger(), nullable=True),
    sa.Column('buyer_rating', sa.SmallInteger(), nullable=True),
    sa.Column('seller_vouch_done', sa.Boolean(), nullable=False),
    sa.Column('buyer_vouch_done', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_deals_buyer', 'deals', ['buyer_id'], unique=False)
    op.create_index('idx_deals_listing', 'deals', ['listing_id'], unique=False)
    op.create_index('idx_deals_seller', 'deals', ['seller_id'], unique=False)
    op.create_index('idx_deals_status', 'deals', ['status'], unique=False)
    op.create_table('event_interests',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'user_id')
    )
    op.create_table('listing_saves',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'listing_id')
    )
    op.create_table('posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('images', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('ref_item_id', sa.UUID(), nullable=True),
    sa.Column('ref_listing_id', sa.UUID(), nullable=True),
    sa.Column('community_id', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('comments_count', sa.Integer(), nullable=False),
    sa.Column('saves_count', sa.Integer(), nullable=False),
    sa.Column('review_rating', sa.SmallInteger(), nullable=True),
    sa.Column('poll_options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_admin_post', sa.Boolean(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.ForeignKeyConstraint(['ref_item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['ref_listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_posts_category', 'posts', ['category'], unique=False)
    op.create_index('idx_posts_community', 'posts', ['community_id'], unique=False)
    op.create_index('idx_posts_created', 'posts', ['created_at'], unique=False)
    op.create_index('idx_posts_type', 'posts', ['type'], unique=False)
    op.create_index('idx_posts_user', 'posts', ['user_id'], unique=False)
    op.create_table('threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('participant_a', sa.UUID(), nullable=False),
    sa.Column('participant_b', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unread_a', sa.Integer(), nullable=False),
    sa.Column('unread_b', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['participant_a'], ['users.id'], ),
    sa.ForeignKeyConstraint(['participant_b'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participant_a', 'participant_b', name='uq_thread_participants')
    )
    op.create_index('idx_threads_a', 'threads', ['participant_a', 'last_message_at'], unique=False)
    op.create_index('idx_threads_b', 'threads', ['participant_b', 'last_message_at'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comments_parent', 'comments', ['parent_id'], unique=False)
    op.create_index('idx_comments_post', 'comments', ['post_id', 'created_at'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('offer_item_id', sa.UUID(), nullable=True),
    sa.Column('is_deal_init', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['offer_item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_thread', 'messages', ['thread_id', 'created_at'], unique=False)
    op.create_table('post_likes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.create_table('post_saves',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.create_table('vouches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_user_id', sa.UUID(), nullable=False),
    sa.Column('to_user_id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_user_id', 'deal_id', name='uq_vouch_per_deal')
    )
    op.create_index('idx_vouches_from_user', 'vouches', ['from_user_id'], unique=False)
    op.create_index('idx_vouches_to_user', 'vouches', ['to_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_vouches_to_user', table_name='vouches')
    op.drop_index('idx_vouches_from_user', table_name='vouches')
    op.drop_table('vouches')
    op.drop_table('post_saves')
    op.drop_table('post_likes')
    op.drop_index('idx_messages_thread', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_comments_post', table_name='comments')
    op.drop_index('idx_comments_parent', table_name='comments')
    op.drop_table('comments')
    op.drop_index('idx_threads_b', table_name='threads')
    op.drop_index('idx_threads_a', table_name='threads')
    op.drop_table('threads')
    op.drop_index('idx_posts_user', table_name='posts')
    op.drop_index('idx_posts_type', table_name='posts')
    op.drop_index('idx_posts_created', table_name='posts')
    op.drop_index('idx_posts_community', table_name='posts')
    op.drop_index('idx_posts_category', table_name='posts')
    op.drop_table('posts')
    op.drop_table('listing_saves')
    op.drop_table('event_interests')
    op.drop_index('idx_deals_status', table_name='deals')
    op.drop_index('idx_deals_seller', table_name='deals')
    op.drop_index('idx_deals_listing', table_name='deals')
    op.drop_index('idx_deals_buyer', table_name='deals')
    op.drop_table('deals')
    op.drop_index('idx_searches_user', table_name='saved_searches')
    op.drop_index('idx_searches_sku', table_name='saved_searches')
    op.drop_table('saved_searches')
    op.drop_index('idx_listings_status', table_name='listings')
    op.drop_index('idx_listings_sku', table_name='listings')
    op.drop_index('idx_listings_seller', table_name='listings')
    op.drop_index('idx_listings_created', table_name='listings')
    op.drop_table('listings')
    op.drop_index('idx_photos_item', table_name='item_photos')
    op.drop_table('item_photos')
    op.drop_index('idx_events_community', table_name='events')
    op.drop_index('idx_events_category', table_name='events')
    op.drop_table('events')
    op.drop_table('community_members')
    op.drop_table('community_join_requests')
    op.drop_table('user_blocks')
    op.drop_index('idx_reports_target', table_name='reports')
    op.drop_index('idx_reports_status', table_name='reports')
    op.drop_table('reports')
    op.drop_index('idx_notifs_user', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_items_verify', table_name='items')
    op.drop_index('idx_items_user', table_name='items')
    op.drop_index('idx_items_status', table_name='items')
    op.drop_index('idx_items_sku', table_name='items')
    op.drop_table('items')
    op.drop_table('communities')
    op.drop_index('idx_users_handle', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_follows_target', table_name='follows')
    op.drop_index('idx_follows_follower', table_name='follows')
    op.drop_table('follows')
    op.drop_index('idx_catalogue_category', table_name='catalogue')
    op.drop_index('idx_catalogue_brand', table_name='catalogue')
    op.drop_table('catalogue')
    # ### end Alembic commands ###
