"""Cities table — dynamic canonical city list for CityField.

Founder (2026-09-06): the onboarding city list must be dynamic. The v8 port
shipped it as a frozen frontend constant, so growing the list meant a frontend
deploy. This moves the canonical list server-side (GET /v1/cities) — adding a
city becomes a DB insert. Seed rows below are the full v8 CityPicker list
(city, region, country, aliases); `popularity` ranks the empty-query defaults
(major metros first) instead of the old "first 8 rows of the array".

Revision ID: f2d5e8b1c6a7
Revises: d3e8f1c6a9b4
Create Date: 2026-09-06
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "f2d5e8b1c6a7"
down_revision: Union[str, None] = "d3e8f1c6a9b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# (name, region, country, aliases-csv, popularity) — aliases lowercase, searchable only.
SEED: list[tuple[str, str | None, str, str | None, int]] = [
    # India — metros carry popularity so the empty-query dropdown shows them first.
    ("Mumbai", "Maharashtra", "India", "bombay", 100),
    ("Delhi", "Delhi", "India", "ncr", 99),
    ("Bengaluru", "Karnataka", "India", "bangalore,blr", 98),
    ("Hyderabad", "Telangana", "India", "hyd", 97),
    ("Chennai", "Tamil Nadu", "India", "madras", 96),
    ("Kolkata", "West Bengal", "India", "calcutta", 95),
    ("Pune", "Maharashtra", "India", "poona", 94),
    ("Ahmedabad", "Gujarat", "India", "amdavad", 93),
    ("New Delhi", "Delhi", "India", None, 0),
    ("Nagpur", "Maharashtra", "India", None, 0),
    ("Nashik", "Maharashtra", "India", None, 0),
    ("Thane", "Maharashtra", "India", None, 0),
    ("Navi Mumbai", "Maharashtra", "India", None, 0),
    ("Mysuru", "Karnataka", "India", "mysore", 0),
    ("Mangaluru", "Karnataka", "India", "mangalore", 0),
    ("Hubballi", "Karnataka", "India", "hubli", 0),
    ("Coimbatore", "Tamil Nadu", "India", None, 0),
    ("Madurai", "Tamil Nadu", "India", None, 0),
    ("Tiruchirappalli", "Tamil Nadu", "India", "trichy", 0),
    ("Warangal", "Telangana", "India", None, 0),
    ("Howrah", "West Bengal", "India", None, 0),
    ("Siliguri", "West Bengal", "India", None, 0),
    ("Surat", "Gujarat", "India", None, 0),
    ("Vadodara", "Gujarat", "India", "baroda", 0),
    ("Rajkot", "Gujarat", "India", None, 0),
    ("Jaipur", "Rajasthan", "India", None, 0),
    ("Jodhpur", "Rajasthan", "India", None, 0),
    ("Udaipur", "Rajasthan", "India", None, 0),
    ("Kota", "Rajasthan", "India", None, 0),
    ("Lucknow", "Uttar Pradesh", "India", None, 0),
    ("Kanpur", "Uttar Pradesh", "India", None, 0),
    ("Noida", "Uttar Pradesh", "India", None, 0),
    ("Ghaziabad", "Uttar Pradesh", "India", None, 0),
    ("Agra", "Uttar Pradesh", "India", None, 0),
    ("Varanasi", "Uttar Pradesh", "India", "banaras", 0),
    ("Prayagraj", "Uttar Pradesh", "India", "allahabad", 0),
    ("Meerut", "Uttar Pradesh", "India", None, 0),
    ("Gurugram", "Haryana", "India", "gurgaon", 0),
    ("Faridabad", "Haryana", "India", None, 0),
    ("Panchkula", "Haryana", "India", None, 0),
    ("Chandigarh", "Chandigarh", "India", None, 0),
    ("Ludhiana", "Punjab", "India", None, 0),
    ("Amritsar", "Punjab", "India", None, 0),
    ("Jalandhar", "Punjab", "India", None, 0),
    ("Bhopal", "Madhya Pradesh", "India", None, 0),
    ("Indore", "Madhya Pradesh", "India", None, 0),
    ("Jabalpur", "Madhya Pradesh", "India", None, 0),
    ("Gwalior", "Madhya Pradesh", "India", None, 0),
    ("Patna", "Bihar", "India", None, 0),
    ("Gaya", "Bihar", "India", None, 0),
    ("Kochi", "Kerala", "India", "cochin,ernakulam", 0),
    ("Thiruvananthapuram", "Kerala", "India", "trivandrum", 0),
    ("Kozhikode", "Kerala", "India", "calicut", 0),
    ("Thrissur", "Kerala", "India", None, 0),
    ("Bhubaneswar", "Odisha", "India", None, 0),
    ("Cuttack", "Odisha", "India", None, 0),
    ("Guwahati", "Assam", "India", None, 0),
    ("Raipur", "Chhattisgarh", "India", None, 0),
    ("Ranchi", "Jharkhand", "India", None, 0),
    ("Jamshedpur", "Jharkhand", "India", None, 0),
    ("Dehradun", "Uttarakhand", "India", None, 0),
    ("Shimla", "Himachal Pradesh", "India", None, 0),
    ("Srinagar", "Jammu & Kashmir", "India", None, 0),
    ("Jammu", "Jammu & Kashmir", "India", None, 0),
    ("Visakhapatnam", "Andhra Pradesh", "India", "vizag", 0),
    ("Vijayawada", "Andhra Pradesh", "India", None, 0),
    ("Guntur", "Andhra Pradesh", "India", None, 0),
    ("Goa", "Goa", "India", "panaji", 0),
    ("Puducherry", "Puducherry", "India", "pondicherry", 0),
    ("Imphal", "Manipur", "India", None, 0),
    ("Shillong", "Meghalaya", "India", None, 0),
    ("Agartala", "Tripura", "India", None, 0),
    ("Aizawl", "Mizoram", "India", None, 0),
    ("Kohima", "Nagaland", "India", None, 0),
    ("Gangtok", "Sikkim", "India", None, 0),
    ("Itanagar", "Arunachal Pradesh", "India", None, 0),
    # Asia-Pacific
    ("Singapore", None, "Singapore", "sg", 10),
    ("Hong Kong", None, "Hong Kong SAR", "hk", 0),
    ("Tokyo", "Kantō", "Japan", None, 10),
    ("Osaka", "Kansai", "Japan", None, 0),
    ("Kyoto", "Kansai", "Japan", None, 0),
    ("Nagoya", "Chūbu", "Japan", None, 0),
    ("Yokohama", "Kantō", "Japan", None, 0),
    ("Seoul", None, "South Korea", None, 0),
    ("Busan", None, "South Korea", None, 0),
    ("Taipei", None, "Taiwan", None, 0),
    ("Kaohsiung", None, "Taiwan", None, 0),
    ("Shanghai", None, "China", None, 0),
    ("Beijing", None, "China", "peking", 0),
    ("Shenzhen", None, "China", None, 0),
    ("Guangzhou", None, "China", "canton", 0),
    ("Chengdu", None, "China", None, 0),
    ("Bangkok", None, "Thailand", None, 0),
    ("Kuala Lumpur", None, "Malaysia", "kl", 0),
    ("Penang", None, "Malaysia", None, 0),
    ("Jakarta", None, "Indonesia", None, 0),
    ("Manila", None, "Philippines", None, 0),
    ("Ho Chi Minh City", None, "Vietnam", "saigon", 0),
    ("Hanoi", None, "Vietnam", None, 0),
    ("Sydney", "New South Wales", "Australia", None, 0),
    ("Melbourne", "Victoria", "Australia", None, 0),
    ("Brisbane", "Queensland", "Australia", None, 0),
    ("Perth", "Western Australia", "Australia", None, 0),
    ("Auckland", None, "New Zealand", None, 0),
    ("Wellington", None, "New Zealand", None, 0),
    ("Colombo", None, "Sri Lanka", None, 0),
    ("Kathmandu", None, "Nepal", None, 0),
    ("Dhaka", None, "Bangladesh", None, 0),
    ("Karachi", None, "Pakistan", None, 0),
    ("Lahore", None, "Pakistan", None, 0),
    ("Islamabad", None, "Pakistan", None, 0),
    # Middle East & Africa
    ("Dubai", None, "United Arab Emirates", "uae", 10),
    ("Abu Dhabi", None, "United Arab Emirates", None, 0),
    ("Sharjah", None, "United Arab Emirates", None, 0),
    ("Doha", None, "Qatar", None, 0),
    ("Riyadh", None, "Saudi Arabia", None, 0),
    ("Jeddah", None, "Saudi Arabia", None, 0),
    ("Kuwait City", None, "Kuwait", None, 0),
    ("Manama", None, "Bahrain", None, 0),
    ("Muscat", None, "Oman", None, 0),
    ("Tel Aviv", None, "Israel", None, 0),
    ("Istanbul", None, "Turkey", None, 0),
    ("Cairo", None, "Egypt", None, 0),
    ("Nairobi", None, "Kenya", None, 0),
    ("Lagos", None, "Nigeria", None, 0),
    ("Johannesburg", None, "South Africa", "jozi", 0),
    ("Cape Town", None, "South Africa", None, 0),
    # Europe
    ("London", "England", "United Kingdom", "uk", 10),
    ("Manchester", "England", "United Kingdom", None, 0),
    ("Birmingham", "England", "United Kingdom", None, 0),
    ("Glasgow", "Scotland", "United Kingdom", None, 0),
    ("Edinburgh", "Scotland", "United Kingdom", None, 0),
    ("Dublin", None, "Ireland", None, 0),
    ("Paris", "Île-de-France", "France", None, 0),
    ("Lyon", None, "France", None, 0),
    ("Marseille", None, "France", None, 0),
    ("Berlin", None, "Germany", None, 0),
    ("Munich", "Bavaria", "Germany", "münchen", 0),
    ("Frankfurt", None, "Germany", None, 0),
    ("Hamburg", None, "Germany", None, 0),
    ("Cologne", None, "Germany", "köln", 0),
    ("Amsterdam", None, "Netherlands", None, 0),
    ("Rotterdam", None, "Netherlands", None, 0),
    ("Brussels", None, "Belgium", None, 0),
    ("Zürich", None, "Switzerland", "zurich", 0),
    ("Geneva", None, "Switzerland", None, 0),
    ("Vienna", None, "Austria", "wien", 0),
    ("Madrid", None, "Spain", None, 0),
    ("Barcelona", None, "Spain", None, 0),
    ("Lisbon", None, "Portugal", "lisboa", 0),
    ("Rome", None, "Italy", "roma", 0),
    ("Milan", None, "Italy", "milano", 0),
    ("Stockholm", None, "Sweden", None, 0),
    ("Copenhagen", None, "Denmark", None, 0),
    ("Oslo", None, "Norway", None, 0),
    ("Helsinki", None, "Finland", None, 0),
    ("Warsaw", None, "Poland", None, 0),
    ("Prague", None, "Czechia", None, 0),
    ("Budapest", None, "Hungary", None, 0),
    ("Athens", None, "Greece", None, 0),
    # Americas
    ("New York", "New York", "United States", "nyc,new york city", 10),
    ("Los Angeles", "California", "United States", "la", 0),
    ("San Francisco", "California", "United States", "sf", 0),
    ("San Jose", "California", "United States", None, 0),
    ("San Diego", "California", "United States", None, 0),
    ("Chicago", "Illinois", "United States", None, 0),
    ("Houston", "Texas", "United States", None, 0),
    ("Dallas", "Texas", "United States", None, 0),
    ("Austin", "Texas", "United States", None, 0),
    ("Seattle", "Washington", "United States", None, 0),
    ("Portland", "Oregon", "United States", None, 0),
    ("Boston", "Massachusetts", "United States", None, 0),
    ("Philadelphia", "Pennsylvania", "United States", None, 0),
    ("Atlanta", "Georgia", "United States", None, 0),
    ("Miami", "Florida", "United States", None, 0),
    ("Orlando", "Florida", "United States", None, 0),
    ("Denver", "Colorado", "United States", None, 0),
    ("Phoenix", "Arizona", "United States", None, 0),
    ("Las Vegas", "Nevada", "United States", None, 0),
    ("Washington", "District of Columbia", "United States", "dc", 0),
    ("Toronto", "Ontario", "Canada", None, 0),
    ("Vancouver", "British Columbia", "Canada", None, 0),
    ("Montreal", "Quebec", "Canada", None, 0),
    ("Calgary", "Alberta", "Canada", None, 0),
    ("Ottawa", "Ontario", "Canada", None, 0),
    ("Mexico City", None, "Mexico", "cdmx", 0),
    ("São Paulo", None, "Brazil", "sao paulo", 0),
    ("Rio de Janeiro", None, "Brazil", "rio", 0),
    ("Buenos Aires", None, "Argentina", None, 0),
    ("Santiago", None, "Chile", None, 0),
    ("Bogotá", None, "Colombia", "bogota", 0),
    ("Lima", None, "Peru", None, 0),
]


def upgrade() -> None:
    table = op.create_table(
        "cities",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("name", sa.String(80), nullable=False),
        sa.Column("region", sa.String(80), nullable=True),
        sa.Column("country", sa.String(80), nullable=False),
        sa.Column("aliases", sa.String(200), nullable=True),
        sa.Column("popularity", sa.Integer(), nullable=False, server_default="0"),
        sa.UniqueConstraint("name", "country", name="uq_city_name_country"),
    )
    op.create_index("idx_cities_popularity", "cities", ["popularity"])
    op.bulk_insert(table, [
        {"name": n, "region": r, "country": c, "aliases": a, "popularity": p}
        for (n, r, c, a, p) in SEED
    ])


def downgrade() -> None:
    op.drop_index("idx_cities_popularity", table_name="cities")
    op.drop_table("cities")
